Repository imgix/luminous, pull requests merged in 2018-06, with the labels that each got.

#55 chore: cache node_modules
  .travis.yml
Labels: Type: Maintenance

#47 Use of const instead of let when possible
  src/js/Lightbox.js
  src/js/Luminous.js
  src/js/LuminousGallery.js
  src/js/injectBaseStylesheet.js
Labels: Type: Maintenance

#58 fix: use the right lettercase, add npm start
  .gitignore
  CONTRIBUTING.md
  dist/Luminous.js
  dist/Luminous.min.js
  package-lock.json
  package.json
Labels: Status: Discussion, Type: Maintenance

#54 chore: add Node.js 6, 8 and 10, remove Node.js 4
  .travis.yml
Labels: Priority: Low, Status: Discussion, Type: Maintenance
